### PR TITLE
Bug/pending verification

### LINKED ISSUE #83: If the user is valided but doesn't belong to a workshop . . .
. . . then, if the user refreshed the page, it hangs on the loading component.

User should still see the pending verification view unless a workshop has been assigned to them.

Let's get rid of the isVerified boolean check from the conditional logic in the UI to simplify the solution:

- [x] Render the workshop index once the user is added to a workshop.
- [x] Delete the isVerified boolean data type from Prisma schema.
- [x] Run the migration with `npx prisma db push`

### PR DESCRIPTION
**Pull request by H-b8**
- removed isVerified from user schema
- user now sees pending until they are added to at least one workshop
- refactors prompts index so that "Loading" shows instead of "No prompts yet" (and then showing them after) while fetching prompts
- added cursor pointer to prompt and posts

Resolves #83

### CODE REVIEW

File: pages/workshop/[wid]/prompt/index.js [hunk 1]
```diff
@@ -19,42 +19,44 @@ const Prompts = (props) => {
...
+        <div className={Styles.promptIndexContainer}>
+          <header>
+            <h1 className={Styles.pageh1}>Prompts</h1>
+            {user.isInstructor ? <button onClick={() => addNew()} className={Styles.addButton}>+</button> : ''}
+          </header>
+
+          {promptsLoading
+            ? <p>Loading . . .</p>
+            : prompts.length > 0
+              ? <main>
```
Comment (MilcahHalili) [inline pages/workshop/[wid]/prompt/index.js:45]: Nice, thanks for debugging this!

**Review by MilcahHalili — APPROVED** [review]
Thanks so much, @H-b8!
